---
- hosts: localhost
  name: Setup ONTAP
  gather_facts: false
  vars_files:
   vars.yml
  vars_prompt:
  - name: "netapp_password"
    prompt: "Password:"
  - name: "vol_name"
    prompt: "Enter the volume name:"
    private: no
  - name: "aggr_name"
    prompt: "Enter the aggr name:"
    private: no
  - name: "vol_size"
    prompt: "Enter the size in gb:"
    private: no
  vars:
    volname: "{{ vol_name }}"
    vserver: "{{ vserver }}"
    state: "{{ state }}"
  tasks:
  - name: Create Volume
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ vol_name }}"
      aggregate_name: "{{ aggr_name }}"
      size: "{{ vol_size }}"
      size_unit: gb
      junction_path: /{{ vol_name }}
      vserver: "{{ vserver }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
  - name: Create CIFS share
    na_ontap_cifs:
      state: "{{ state }}"
      path: /{{ vol_name }}
      share_name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
