---
- hosts: localhost
  name: create_aggregate
  vars_files:
    vars.yml
  vars_prompt:
  - name: "netapp_password"
    prompt: "Password:"
  tasks:
    - name: Create aggregate 1
      na_ontap_aggregate:
        state: present
        service_state: online
        name: "{{ aggrname1 }}"
        nodes: "{{ node_name_01 }}"
        disk_count: 10
        raid_size: 10
        wait_for_online: true
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"

    - name: Create aggregate 2
      na_ontap_aggregate:
        state: present
        service_state: online
        name: "{{ aggrname2 }}"
        nodes: "{{ node_name_02 }}"
        disk_count: 10
        raid_size: 10
        wait_for_online: true
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
