---
- hosts: localhost
  gather_facts: false
  vars_files:
   vars.yml
  name: Create interface NFS
  tasks:
  - name: Create NFS LIF
    na_ontap_interface:
      state: present
      interface_name: "{{ vserver }}_nfs_data_1"
      home_port: e0c
      home_node: "{{ node_name_01 }}"
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: data
      is_auto_revert: true
      address: "{{ address_nfs2 }}"
      netmask: 255.255.255.0
      vserver: "{{ vserver }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
