---
- hosts: rhel2
  name: Mount volume
  vars:
    rhel_username: root
    rhel_password: Netapp1!
  vars_prompt:
  - name: "volume_name"
    prompt: "Volume name:"
    private: no
  hosts: rhel2
  tasks:
  - name: Create mountpoint
    file:
        path: /mnt/{{ volume_name }}
        state: directory
        mode: 777
        owner: root
        group: root
  - name: Mount NFS Volume
    mount:
        path: /mnt/{{ volume_name }}
        src: 192.168.0.51:/nfs_vol_01
        fstype: nfs
        opts: rw
        state: mounted
