---
- hosts: localhost
  name: Setup ONTAP
  gather_facts: false
  vars_files:
   vars.yml
  vars_prompt:
  - name: "netapp_password"
    prompt: "Password:"
  - name: "vserver"
    prompt: "Enter the vserver name:"
    private: no
  - name: "vol_name"
    prompt: "Enter the volume name:"
    private: no
  - name: "aggr_name"
    prompt: "Enter the aggr name:"
    private: no
  - name: "vol_size"
    prompt: "Enter the new size:"
    private: no
  vars:
    policy: "{{ vol_name }}_policy"
    state: "{{ state }}"
  tasks:
  - name: Change volume size
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ vol_name }}"
      aggregate_name: "{{ aggr_name }}"
      size: "{{ vol_size }}"
      size_unit: gb
      vserver: "{{ vserver }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
